### ISSUE TITLE
:O Cat? On CLICKGUI? HELL YEA

### ISSUE THREAD

**Issue by SpaceLightningExpress** [Cvrwed/Haru#1]

**Comment by Cvrwed** [comment]
One of many

**Comment by atomiciscool** [comment]
> One of many

Can u add support to weave loader for it ?

**Comment by Cvrwed** [comment]
I will do it someday

**Comment by atomiciscool** [comment]
> I will do it someday

any discord for it?

**Comment by MathCvrFanL** [comment]
Cvr, add mewing to the client, lol

**Comment by MathCvrFanL** [comment]
Version of the actual version of haru?

**Comment by Cvrwed** [comment]
> Version of the actual version of haru?

Forge 1.8.9

**Comment by atomiciscool** [comment]
> > Version of the actual version of haru?
> 
> Forge 1.8.9

is there a discord

**Comment by Cvrwed** [comment]
> > > Version of the actual version of haru?
> > 
> > 
> > Forge 1.8.9
> 
> is there a discord

Unfortunately not

**Comment by SpaceLightningExpress** [comment]
We have haru client before gta 6 UwU

**Comment by Cvrwed** [comment]
I will put a fact that few people know and that is that you can drag the "waifu" of the clickgui by clicking on it.

**Comment by SpaceLightningExpress** [comment]
> I will put a fact that few people know and that is that you can drag the "waifu" of the clickgui by clicking on it.

Rill

**Comment by Biggestmogger** [comment]
> I will do it someday

No keep it as a forge mod

**Comment by atomiciscool** [comment]
> > I will do it someday
> 
> No keep it as a forge mod

it could be a weave mod and forge broda, ur not logic
