### ISSUE TITLE
CPSDisplay right and left button are overlapping in the newest update

### ISSUE THREAD

**Issue by inckus23x** [Cvrwed/Haru#10]
![xzczcx](https://github.com/Cvrwed/Haru/assets/161126009/9c7e710c-ff78-45e5-9940-9a8b7628265c)
Idk if only I have this problem now because everything was alright before the update. Since I'm reporting something about this module already i have a suggestion to allow edit position of CPSDisplay

**Comment by Cvrwed** [comment]
already fixed just wait for the next release
