### ISSUE TITLE
Disabling Blink is crashing the game

### ISSUE THREAD

**Issue by inckus23x** [Cvrwed/Haru#11]
Tested with **.toggle** command and **ClickGUI** - same result.

Logs while performing a command:

> [13:07:06] [Client thread/INFO]: [CHAT] §f Blink §7§aenabled
> [13:07:10] [Client thread/INFO]: [CHAT] §f Blink §7§cdisabled.
> [13:07:10] [Server thread/INFO]: Player lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.lang.ClassCastException: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1 cannot be cast to net.minecraft.network.play.INetHandlerPlayClient], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
> [13:07:10] [Server thread/INFO]: Player left the game
> [13:07:10] [Server thread/INFO]: Stopping singleplayer server as player logged out
> [13:07:10] [Server thread/INFO]: Stopping server
> [13:07:10] [Server thread/INFO]: Saving players
> [13:07:10] [Server thread/INFO]: Saving worlds
> [13:07:10] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
> [13:07:10] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
> [13:07:10] [Server thread/INFO]: Saving chunks for level 'New World'/The End
> [13:07:10] [Server thread/INFO] [FML]: Unloading dimension 0
> [13:07:10] [Server thread/INFO] [FML]: Unloading dimension -1
> [13:07:10] [Server thread/INFO] [FML]: Unloading dimension 1
> [13:07:10] [Server thread/INFO] [FML]: Applying holder lookups
> [13:07:10] [Server thread/INFO] [FML]: Holder lookups applied
>

**Comment by Cvrwed** [comment]
> Tested with **.toggle** command and **ClickGUI** - same result.
> 
> Logs while performing a command:
> 
> > [13:07:06] [Client thread/INFO]: [CHAT] §f Blink §7§aenabled
> > [13:07:10] [Client thread/INFO]: [CHAT] §f Blink §7§cdisabled.
> > [13:07:10] [Server thread/INFO]: Player lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.lang.ClassCastException: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1 cannot be cast to net.minecraft.network.play.INetHandlerPlayClient], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
> > [13:07:10] [Server thread/INFO]: Player left the game
> > [13:07:10] [Server thread/INFO]: Stopping singleplayer server as player logged out
> > [13:07:10] [Server thread/INFO]: Stopping server
> > [13:07:10] [Server thread/INFO]: Saving players
> > [13:07:10] [Server thread/INFO]: Saving worlds
> > [13:07:10] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
> > [13:07:10] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
> > [13:07:10] [Server thread/INFO]: Saving chunks for level 'New World'/The End
> > [13:07:10] [Server thread/INFO] [FML]: Unloading dimension 0
> > [13:07:10] [Server thread/INFO] [FML]: Unloading dimension -1
> > [13:07:10] [Server thread/INFO] [FML]: Unloading dimension 1
> > [13:07:10] [Server thread/INFO] [FML]: Applying holder lookups
> > [13:07:10] [Server thread/INFO] [FML]: Holder lookups applied

well, that tends to happen in singleplayer, I'm working on fixing it.
