### ISSUE TITLE
JumpReset does nothing?

### ISSUE THREAD

**Issue by notKnownn** [Cvrwed/Haru#26]
https://github.com/Cvrwed/Haru/assets/118249487/72cac6a4-c4e9-4b94-bd6a-bf04c55531fa

Hmmm

**Comment by Cvrwed** [comment]
The more motion you have, the less you will reduce.

**Comment by notKnownn** [comment]
> The more motion you have, the less you will reduce.
> 
> That is, if you have a high value you will not reduce but if you have a low value you will reduce.

![image](https://github.com/Cvrwed/Haru/assets/118249487/e2a9891c-9bbc-489c-8a01-777fab0f43c2)
So with this config it should reduce, right?
I'm trying to get 0 horizontal kb since it's possible when legit playing but every mode and every config I set on jumpReset feels the same

**Comment by Cvrwed** [comment]
It will feel slightly different.

**Comment by notKnownn** [comment]
> Are you referring to the hit and tick mode of liquidbounce's velocity jump? If you have it, it is the tick or hit mode, it will reduce from 2-3 hit/ticks it is already pre-configured although I will add a way to configure it, about the jump reset motion mode apart from motion x/y, it also verifies the player's yaw since it reduces through it

ye that's what I'm talking about. I saw Haru also has hit and tick but liquidbounce's is like more... Perfect? I mean it makes you take vertical kb only (not using any bypass since it's just jump reset). I don't know how it internally works because i'm not that good at programming, but if I test my kb with the module disabled it's feels the same.

I could be missing something... Anyways I'll check the next release whenever it comes out, i'm nervous to test that backtrack
