### ISSUE TITLE
please remove hitcolor 

### ISSUE THREAD

**Issue by Rawywy** [Cvrwed/Haru#29]
la función de hit color no permite que funcione el mod de damagetint

**Comment by Cvrwed** [comment]
Envíame el mod

**Comment by Rawywy** [comment]
[ABRE EL ARCHIVO .zip](https://github.com/Cvrwed/Haru/files/14624907/ABRE.EL.ARCHIVO.zip)

**Comment by Cvrwed** [comment]
Enviame el jar directamente

**Comment by Rawywy** [comment]
No hay forma de que gihub no lo permita
