### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by notKnownn** [Cvrwed/Haru#39]
Add a console in the clickgui where commands will be executed and remove commands from game chat.

In my opinion that would make it more "closet cheating". This feature is from raven b+

**Comment by Cvrwed** [comment]
I don't plan to add that again but I do plan to put in a self-destruct module to compensate for the Command chat.

**Comment by notKnownn** [comment]
> I don't plan to add that again but I do plan to put in a self-destruct module to compensate for the Command chat.

Then what about a .say command? I dont know if that is already in the client but that would allows us to send for example ".hello" to the chat. Some people ask to send something starting with a dot to check if the user is hacker or not.

**Comment by Cvrwed** [comment]
By activating self-destruct you could send a . in the chat
