### ISSUE TITLE
skid aura ravenx and pls add autotool

### ISSUE THREAD

**Issue by namkhanh1123** [Cvrwed/Haru#7]
you can skid aura in ravenx on necakco channel

**Comment by Cvrwed** [comment]
send

**Comment by namkhanh1123** [comment]
https://cheatcl.web.app/ravenx/rvx

**Comment by namkhanh1123** [comment]
[Uploading Neven-main.zip…]()
here is source

**Comment by namkhanh1123** [comment]
pls dont add aura from skid it so goffy
