### ISSUE TITLE
better backtrack 

### ISSUE THREAD

**Issue by Rawywy** [Cvrwed/Haru#71]
poner el backtrack de haru 2.34.1 a haru 2.37

**Comment by Cvrwed** [comment]
It is the same, it only brings more options but the current one is being improved

**Comment by Rawywy** [comment]
No es lo mismo solo me molesta, el de haru 2.37, el de 2.34.1 funciona bien

**Comment by Cvrwed** [comment]
I already saw what this backtrack was changed because it currently does not work in some acs including grim

**Comment by Rawywy** [comment]
Ok
