### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by aoehakDoc** [Cvrwed/Haru#73]
Yo Cvrwed I see you've made v2.38 already, but can you pls upload it as a forge mod in the releases? Some of us are dumbfucks who don't know anything about coding and can't unpack the srcs on their own.

**Comment by Cvrwed** [comment]
Release on discord

**Comment by aoehakDoc** [comment]
oh ok thnx

**Comment by aoehakDoc** [comment]
yay thnx cvrwed u uploaded i luv u ur the best 💜
