### ISSUE TITLE
Labymod

### ISSUE THREAD

**Issue by Idklol5668** [Cvrwed/Haru#74]
All modules on forge Labymod 1.8.9 work fine other than visuals (ESP, Nametags etc) is there a way these could be made compatible?

**Comment by Idklol5668** [comment]
That clien't wont even launch for me can i send forge logs instead?

**Comment by Cvrwed** [comment]
send it

**Comment by Idklol5668** [comment]
Fixed it reinstalling labymod somehow sorry for the time waste
