### ISSUE TITLE
Add Tick click event for Left Clicker (and Right Clicker)

### ISSUE THREAD

**Issue by inckus23x** [Cvrwed/Haru#8]
![DyZ83l](https://github.com/Cvrwed/Haru/assets/161126009/3999b73d-b990-466a-bc05-3929d50fa5b6)
Add Tick click event for Left Clicker. **Raven b+** has this feature (https://github.com/Kopamed/Raven-bPLUS)
You can also add "SKid" click style because i use it a lot on some servers. pls :))

**Comment by Cvrwed** [comment]
Kuru style > SKid style

**Comment by inckus23x** [comment]
What about Tick click event? Do you have plans on adding it?

**Comment by Cvrwed** [comment]
> What about Tick click event? Do you have plans on adding it?

I just added it just now
